### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by zikalino** [Azure/magic-module-specs#70]
I am trying to compile "batchaccount" and I am getting following error message.

Message is not very clear, it's hard to figure out what is actually wrong.
There's  also no line number in source api.yaml file which would help to investigate problem.

D, [2019-07-05T08:05:59.791878 #6] DEBUG -- : Compiling templates/azure/ansible/sdktypes/property_normalize.erb
D, [2019-07-05T08:05:59.793019 #6] DEBUG -- : Compiling templates/azure/ansible/sdktypes/reference_assignment.erb
D, [2019-07-05T08:05:59.793900 #6] DEBUG -- : Compiling templates/azure/ansible/sdktypes/reference_assignment.erb
Error compiling file: templates/azure/ansible/resource.erb
bundler: failed to load command: compiler (compiler)
NoMethodError: undefined method `python_field_name' for nil:NilClass
  (erb):5:in `build_sdk_reference_assignment'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `result'
  /magic-modules/compile/core.rb:148:in `compile'
  /magic-modules/provider/azure/ansible/sdk/sub_template.rb:17:in `build_sdk_reference_assignment'
  (erb):13:in `build_sdk_reference_assignment'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `result'
  /magic-modules/compile/core.rb:148:in `compile'
  /magic-modules/provider/azure/ansible/sdk/sub_template.rb:17:in `build_sdk_reference_assignment'
  (erb):33:in `build_property_normalization'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `result'
  /magic-modules/compile/core.rb:148:in `compile'
  /magic-modules/provider/azure/ansible/sdk/sub_template.rb:13:in `build_property_normalization'
  (erb):20:in `block in build_property_to_sdk_object'
  (erb):11:in `each'
  (erb):11:in `build_property_to_sdk_object'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `result'
  /magic-modules/compile/core.rb:148:in `compile'
  /magic-modules/provider/azure/ansible/sdk/sub_template.rb:22:in `build_property_to_sdk_object'
  (erb):82:in `provider_binding'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `eval'
  /usr/lib/ruby/2.6.0/erb.rb:901:in `result'
  /magic-modules/compile/core.rb:237:in `compile_string'
  /magic-modules/compile/core.rb:172:in `compile_file'
  /magic-modules/provider/core.rb:99:in `block in generate'
  /magic-modules/provider/core.rb:99:in `open'
  /magic-modules/provider/core.rb:99:in `generate'
  /magic-modules/provider/azure/ansible_extension.rb:43:in `azure_generate_resource'
  /magic-modules/provider/ansible.rb:239:in `generate_resource'
  /magic-modules/provider/core.rb:312:in `generate_object'
  /magic-modules/provider/core.rb:303:in `block in generate_objects'
  /magic-modules/provider/core.rb:282:in `each'
  /magic-modules/provider/core.rb:282:in `generate_objects'
  /magic-modules/provider/ansible.rb:313:in `generate_objects'
  /magic-modules/provider/core.rb:182:in `generate'
  compiler:150:in `block in <top (required)>'
  compiler:102:in `each'
  compiler:102:in `<top (required)>'

**Comment by JunyiYi** [comment]
You are right, MM does not have a good error handling strategy. The only hint would be the stacktrace. For example in your log, I would go to **`templates/azure/ansible/sdktypes/reference_assignment.erb`** (because this is the top `erb` file appeared in the stacktrace), and look at the code at **line 5** (which is mentioned in log message `undefined method python_field_name for nil:NilClass (erb):5`):

```ruby
output_expression = "#{sdk_marshal.marshalled_references[parent_ref]}['#{sdk_type.python_field_name}']"
```

From the code I can tell we are missing `python_field_name` attribute for some property in `api.yaml`.
